 name: ModerationPlugin
 version: 1.0.0
 description: plugin for Moderator
 main: fr.mrallan140.modplug.Main
 commands:
  modgui:
    description: Ouvre le menu du plugin.
    usage: /modgui
    permission: modplug.gui